# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        stages: [commit]
    -   id: end-of-file-fixer
        stages: [commit]
    -   id: check-yaml
        stages: [commit]
    -   id: check-added-large-files
        args: ["--maxkb=8192"]
        stages: [commit]
    -   id: detect-private-key
        stages: [commit]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        # max-line-length setting is the same as black
        # commit cannot be done when cyclomatic complexity is more than 10.
        args: ["--max-line-length", "88", "--ignore=E402, W503", "--max-complexity", "10", "--max-expression-complexity=15", "--max-cognitive-complexity=15"]
        additional_dependencies: [flake8-bugbear, flake8-builtins, flake8-eradicate, pep8-naming, flake8-expression-complexity, flake8-cognitive-complexity]
